import { GoogleGenAI, Type } from "@google/genai";

let aiClient: GoogleGenAI | null = null;

const getGenAIClient = () => {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not defined. Please configure your API key.");
    }
    aiClient = new GoogleGenAI({ apiKey });
  }
  return aiClient;
};

export const generateLogoImage = async (companyDescription: string): Promise<string> => {
  const client = getGenAIClient();
  
  const prompt = `A professional, minimalist, scalable vector-style logo design based on this company description: 
"${companyDescription}". 
The logo MUST be isolated on a pure white background. Flat colors, clear simple shapes, negative space. No complex realistic details, no text. Perfect for a startup identity.`;
  
  const response = await client.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { text: prompt },
      ],
    },
  });

  if (response?.candidates && response.candidates.length > 0) {
    const parts = response.candidates[0].content.parts;
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        const mimeType = part.inlineData.mimeType || 'image/png';
        return `data:${mimeType};base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error("No image generated by the AI model. Please try another description.");
};

export interface BrandColor {
  hex: string;
  name: string;
  usage: string;
}

export interface BrandGuide {
  brandName: string;
  primaryColors: BrandColor[];
  secondaryColors: BrandColor[];
  typography: {
    primaryFont: string;
    secondaryFont: string;
    guidelines: string;
  };
  logoUsage: {
    clearSpace: string;
    minimumSize: string;
    doNot: string[];
  };
  brandVoice: {
    tone: string;
    keywords: string[];
    description: string;
  };
}

export interface RefinementSuggestion {
  layoutImprovements: string[];
  vectorAdjustments: string[];
  colorAlternatives: BrandColor[];
  refinedLogoPrompt: string;
}

export const analyzeRefinementContext = async (
  originalLogoBase64: string,
  originalLogoMimeType: string,
  contextFiles: { base64Data: string; mimeType: string }[] // Could be pdf, image, text
): Promise<RefinementSuggestion> => {
  const client = getGenAIClient();
  
  const prompt = `You are a master brand designer. Analyze the provided original logo and the provided contextual instruction files (which might be PDFs, text, or images outlining new requirements).
Suggest concrete layout improvements, vector adjustments, and color alternatives.
Crucially, write a 'refinedLogoPrompt' which is a highly detailed text-to-image prompt that we can use to generate the improved version of this logo. Ensure the new prompt incorporates the requested changes while retaining the core recognizable essence of the original logo.`;

  const parts: any[] = [
    { text: prompt },
    { inlineData: { data: originalLogoBase64, mimeType: originalLogoMimeType } }
  ];

  contextFiles.forEach(file => {
    parts.push({ inlineData: { data: file.base64Data, mimeType: file.mimeType } });
  });

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: {
      parts
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          layoutImprovements: { type: Type.ARRAY, items: { type: Type.STRING } },
          vectorAdjustments: { type: Type.ARRAY, items: { type: Type.STRING } },
          colorAlternatives: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                hex: { type: Type.STRING },
                name: { type: Type.STRING },
                usage: { type: Type.STRING }
              },
              required: ["hex", "name", "usage"]
            }
          },
          refinedLogoPrompt: { type: Type.STRING }
        },
        required: ["layoutImprovements", "vectorAdjustments", "colorAlternatives", "refinedLogoPrompt"]
      }
    }
  });

  if (response.text) {
    try {
      return JSON.parse(response.text.trim()) as RefinementSuggestion;
    } catch (e) {
      throw new Error("Failed to parse refinement suggestions.");
    }
  }

  throw new Error("No content generated for refinement.");
};

export const generateBrandGuide = async (
  base64Data: string,
  mimeType: string,
  context?: string
): Promise<BrandGuide> => {
  const client = getGenAIClient();
  
  const prompt = `Analyze this logo and generate a comprehensive, professional brand guideline document. ${context ? `The company context is: "${context}".` : "Infer the brand's industry and vibe from the logo itself."} Return the results in the requested JSON structure. Provide realistic, high-quality, actionable advice suitable for a real design system. Ensure colors match the primary features in the uploaded image accurately.`;

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: {
      parts: [
        { text: prompt },
        { inlineData: { data: base64Data, mimeType } }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          brandName: { type: Type.STRING, description: "Inferred or provided brand name" },
          primaryColors: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                hex: { type: Type.STRING, description: "Hex code, e.g., #FFFFFF" },
                name: { type: Type.STRING, description: "Creative name for the color" },
                usage: { type: Type.STRING, description: "Where to use this color" }
              },
              required: ["hex", "name", "usage"]
            }
          },
          secondaryColors: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                hex: { type: Type.STRING },
                name: { type: Type.STRING },
                usage: { type: Type.STRING }
              },
              required: ["hex", "name", "usage"]
            }
          },
          typography: {
            type: Type.OBJECT,
            properties: {
              primaryFont: { type: Type.STRING },
              secondaryFont: { type: Type.STRING },
              guidelines: { type: Type.STRING }
            },
            required: ["primaryFont", "secondaryFont", "guidelines"]
          },
          logoUsage: {
            type: Type.OBJECT,
            properties: {
              clearSpace: { type: Type.STRING },
              minimumSize: { type: Type.STRING },
              doNot: { type: Type.ARRAY, items: { type: Type.STRING } }
            },
            required: ["clearSpace", "minimumSize", "doNot"]
          },
          brandVoice: {
            type: Type.OBJECT,
            properties: {
              tone: { type: Type.STRING },
              keywords: { type: Type.ARRAY, items: { type: Type.STRING } },
              description: { type: Type.STRING }
            },
            required: ["tone", "keywords", "description"]
          }
        },
        required: ["brandName", "primaryColors", "secondaryColors", "typography", "logoUsage", "brandVoice"]
      }
    }
  });

  if (response.text) {
    try {
      return JSON.parse(response.text.trim()) as BrandGuide;
    } catch (e) {
      throw new Error("Failed to parse brand guide from AI response.");
    }
  }

  throw new Error("No content generated for the brand guide.");
};

export const generateSonicPhilosophy = async (
  companyDescription: string,
  soundNames: string[]
): Promise<string> => {
  const client = getGenAIClient();
  
  const prompt = `You are a master of Organic Sonic Branding. We are forging an auditory identity exclusively from organic, environmental, and animal sounds. No musical instruments.
The company is: "${companyDescription}".
The user has uploaded the following environmental sounds: ${soundNames.join(', ')}.

Write a 2-3 paragraph "Sonic Identity Philosophy" for this brand. Explain how these specific organic sounds represent the brand's core values, their emotional meaning, and how they combine into a cohesive audio sting. Be poetic but professional.`;

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: {
      parts: [
        { text: prompt }
      ]
    }
  });

  if (response.text) {
    return response.text.trim();
  }

  throw new Error("No sonic philosophy generated.");
};
