import { GoogleGenAI, Type } from "@google/genai";
import { useAppStore } from "../store";

let defaultClient: GoogleGenAI | null = null;

const getGenAIClient = () => {
  const customSettings = useAppStore.getState().settings;
  const customKey = customSettings?.geminiKey;
  
  if (customKey) {
    return new GoogleGenAI({ apiKey: customKey });
  }

  if (!defaultClient) {
    const apiKey = process.env.GEMINI_API_KEY || (import.meta as any).env?.VITE_GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("API Key is missing. Please configure your GEMINI_API_KEY in the settings tab.");
    }
    defaultClient = new GoogleGenAI({ apiKey });
  }
  return defaultClient;
};

export const generateLogoImage = async (companyDescription: string): Promise<string> => {
  const client = getGenAIClient();
  
  const prompt = `A professional, minimalist, scalable vector-style logo design based on this company description: 
"${companyDescription}". 
The logo MUST be isolated on a pure white background. Flat colors, clear simple shapes, negative space. No complex realistic details, no text. Perfect for a startup identity.`;
  
  const response = await client.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { text: prompt },
      ],
    },
  });

  if (response?.candidates && response.candidates.length > 0) {
    const parts = response.candidates[0].content.parts;
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        const mimeType = part.inlineData.mimeType || 'image/png';
        return `data:${mimeType};base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error("No image generated by the AI model. Please try another description.");
};

export interface BrandColor {
  hex: string;
  name: string;
  usage: string;
}

export interface BrandGuide {
  brandName: string;
  primaryColors: BrandColor[];
  secondaryColors: BrandColor[];
  typography: {
    primaryFont: string;
    secondaryFont: string;
    guidelines: string;
  };
  logoUsage: {
    clearSpace: string;
    minimumSize: string;
    doNot: string[];
  };
  brandVoice: {
    tone: string;
    keywords: string[];
    description: string;
  };
  photography: string;
  iconography: string;
  dosAndDonts: string[];
}

export interface RefinementSuggestion {
  layoutImprovements: string[];
  vectorAdjustments: string[];
  colorAlternatives: BrandColor[];
  refinedLogoPrompt: string;
}

export const analyzeRefinementContext = async (
  originalLogoBase64: string,
  originalLogoMimeType: string,
  contextFiles: { base64Data: string; mimeType: string }[] // Could be pdf, image, text
): Promise<RefinementSuggestion> => {
  const client = getGenAIClient();
  
  const prompt = `You are a master brand designer. Analyze the provided original logo and the provided contextual instruction files (which might be PDFs, text, or images outlining new requirements).
Suggest concrete layout improvements, vector adjustments, and color alternatives.
Crucially, write a 'refinedLogoPrompt' which is a highly detailed text-to-image prompt that we can use to generate the improved version of this logo. Ensure the new prompt incorporates the requested changes while retaining the core recognizable essence of the original logo.`;

  const parts: any[] = [
    { text: prompt },
    { inlineData: { data: originalLogoBase64, mimeType: originalLogoMimeType } }
  ];

  contextFiles.forEach(file => {
    parts.push({ inlineData: { data: file.base64Data, mimeType: file.mimeType } });
  });

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: {
      parts
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          layoutImprovements: { type: Type.ARRAY, items: { type: Type.STRING } },
          vectorAdjustments: { type: Type.ARRAY, items: { type: Type.STRING } },
          colorAlternatives: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                hex: { type: Type.STRING },
                name: { type: Type.STRING },
                usage: { type: Type.STRING }
              },
              required: ["hex", "name", "usage"]
            }
          },
          refinedLogoPrompt: { type: Type.STRING }
        },
        required: ["layoutImprovements", "vectorAdjustments", "colorAlternatives", "refinedLogoPrompt"]
      }
    }
  });

  if (response.text) {
    try {
      return JSON.parse(response.text.trim()) as RefinementSuggestion;
    } catch (e) {
      throw new Error("Failed to parse refinement suggestions.");
    }
  }

  throw new Error("No content generated for refinement.");
};

export const generateBrandGuide = async (
  base64Data: string,
  mimeType: string,
  context?: string
): Promise<BrandGuide> => {
  const client = getGenAIClient();
  
  const prompt = `Analyze this logo and generate a comprehensive, professional brand guideline document. ${context ? `The company context is: "${context}".` : "Infer the brand's industry and vibe from the logo itself."} Return the results in the requested JSON structure. Provide realistic, high-quality, actionable advice suitable for a real design system. Ensure colors match the primary features in the uploaded image accurately.`;

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: {
      parts: [
        { text: prompt },
        { inlineData: { data: base64Data, mimeType } }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          brandName: { type: Type.STRING, description: "Inferred or provided brand name" },
          primaryColors: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                hex: { type: Type.STRING, description: "Hex code, e.g., #FFFFFF" },
                name: { type: Type.STRING, description: "Creative name for the color" },
                usage: { type: Type.STRING, description: "Where to use this color" }
              },
              required: ["hex", "name", "usage"]
            }
          },
          secondaryColors: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                hex: { type: Type.STRING },
                name: { type: Type.STRING },
                usage: { type: Type.STRING }
              },
              required: ["hex", "name", "usage"]
            }
          },
          typography: {
            type: Type.OBJECT,
            properties: {
              primaryFont: { type: Type.STRING },
              secondaryFont: { type: Type.STRING },
              guidelines: { type: Type.STRING }
            },
            required: ["primaryFont", "secondaryFont", "guidelines"]
          },
          logoUsage: {
            type: Type.OBJECT,
            properties: {
              clearSpace: { type: Type.STRING },
              minimumSize: { type: Type.STRING },
              doNot: { type: Type.ARRAY, items: { type: Type.STRING } }
            },
            required: ["clearSpace", "minimumSize", "doNot"]
          },
          brandVoice: {
            type: Type.OBJECT,
            properties: {
              tone: { type: Type.STRING },
              keywords: { type: Type.ARRAY, items: { type: Type.STRING } },
              description: { type: Type.STRING }
            },
            required: ["tone", "keywords", "description"]
          },
          photography: { type: Type.STRING },
          iconography: { type: Type.STRING },
          dosAndDonts: { type: Type.ARRAY, items: { type: Type.STRING } }
        },
        required: ["brandName", "primaryColors", "secondaryColors", "typography", "logoUsage", "brandVoice", "photography", "iconography", "dosAndDonts"]
      }
    }
  });

  if (response.text) {
    try {
      return JSON.parse(response.text.trim()) as BrandGuide;
    } catch (e) {
      throw new Error("Failed to parse brand guide from AI response.");
    }
  }

  throw new Error("No content generated for the brand guide.");
};

export const generateSonicPhilosophy = async (
  companyDescription: string,
  soundNames: string[]
): Promise<string> => {
  const client = getGenAIClient();
  
  const prompt = `You are a master of Organic Sonic Branding. We are forging an auditory identity exclusively from organic, environmental, and animal sounds. No musical instruments.
The company is: "${companyDescription}".
The user has uploaded the following environmental sounds: ${soundNames.join(', ')}.

Write a 2-3 paragraph "Sonic Identity Philosophy" for this brand. Explain how these specific organic sounds represent the brand's core values, their emotional meaning, and how they combine into a cohesive audio sting. Be poetic but professional.`;

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: {
      parts: [
        { text: prompt }
      ]
    }
  });

  if (response.text) {
    return response.text.trim();
  }

  throw new Error("No sonic philosophy generated.");
};

export const generateDesignRationale = async (description: string, stage: string): Promise<string> => {
  const client = getGenAIClient();
  const prompt = `As a master brand architect and logo designer from the "Srvel" ecosystem, provide an expert educational rationale for a logo design based on this brief: "${description}".
The current stage of the project is: ${stage}.
Explain the psychological choices, shape theory, typography pairings, and color meaning. Address this to a beginner designer using the "Beginex" educational framework to help them understand *why* this works and how to pitch it to clients. Keep it structured, encouraging, and highly professional.`;

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: { parts: [{ text: prompt }] }
  });

  return response.text?.trim() || "Rationale could not be generated.";
};

export const generateAICriticComment = async (
  companyDescription: string,
  logoUrl?: string | null,
  role?: string
): Promise<string> => {
  const client = getGenAIClient();
  const actualRole = role || "Senior Art Director";
  const prompt = `You are playing the role of an elite, highly precise and constructive design critic: a "${actualRole}".
We are designing a logo for this company/brief: "${companyDescription}".
Please write a short, professional, and actionable design critique (2-3 sentences) of the current logo direction. Focus on visual weight, color contrast, metaphorical depth, or industry fit based on your specialty. Be critical but highly constructive and encouraging. Do not mention that you cannot see the image if the image is missing, just critique the concept/potential execution based on the description and any visible design style.`;

  const parts: any[] = [{ text: prompt }];
  if (logoUrl && logoUrl.startsWith('data:')) {
    const base64Data = logoUrl.split(',')[1];
    const mimeTypeMatch = logoUrl.match(/data:(.*?);/);
    const mimeType = mimeTypeMatch ? mimeTypeMatch[1] : 'image/png';
    parts.push({ inlineData: { data: base64Data, mimeType } });
  }

  const response = await client.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: { parts }
  });

  return response.text?.trim() || "Terrific start. Consider checking color values for balanced contrast.";
};

